const x = {
  thead: {
    date: "تاريخ التعاقد",
    collector: "اسم المحصل",
    requiredCollections: "المطلوب تحصيلة",
    collectionsDone: "ما تم تحصيلة",
    areas: "المنطقة/المناطق",
  },
  rows: [
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
    {
      date: "12/2/2022",
      collector: "محمد حسين",
      requiredCollections: 23,
      collectionsDone: 23,
      areas: ["العقاد"],
      receiptNumber: 24123,
    },
  ],
};

export default x;
