const x = {
  thead: {
    contractSerial: "سريال التعاقد",
    clientName: "اسم العميل",
    phone: "رقم الهاتف",
    area: "المنطقة",
    services: "الخدمات",
    status: "حالة التحصيل",
    receiptNumber: "سريال الفاتورة",
  },
  rows: [
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
    {
      contractSerial: "123123",
      clientName: "محمد حسين",
      phone: "01233326751",
      area: "العقاد",
      services: ["جمع منزلي", "رش و تعقيم"],
      status: "تم الحصيل",
      receiptNumber: "123167",
      clientId: 24,
    },
  ],
};

export default x;
